
from scripts.make_params import make
from pathlib import Path

Path("data/params").mkdir(exist_ok=True, parents=True)
for i in range(1000):
    make(i*5)
    #pass

seeds, = glob_wildcards("data/params/{seed, \d+}.yaml")
methods = ["nuance", "wotan_tls"]

# --------------------


wildcard_constraints:
    seed="\d+"

rule:
    input: "figures/wotan_tls_result.png"

rule make_lightcurves:
    input: "data/params/{seed, \d+}.yaml"
    output: "data/lightcurves/{seed}.npy"
    conda: "envs/base.yaml"
    priority: 0
    script: "scripts/make_lightcurve.py"

rule search:
    input: 
        "data/lightcurves/{seed, \d+}.npy",
        "data/params/{seed, \d+}.yaml"
    output: "data/results/{method}/{seed}.yaml"
    conda: "envs/base.yaml"
    priority: 1
    script: "scripts/search_{wildcards.method}.py"

rule plot_lc:
    input: 
        "data/lightcurves/{seed, \d+}.npy"
    output: "figures/lightcurves/{seed}.png"
    conda: "envs/base.yaml"
    script: "scripts/plot_lc.py"

rule detection_results:
    input: 
        params=expand("data/params/{seed}.yaml", seed=seeds),
        nuance=expand("data/results/nuance/{seed}.yaml", seed=seeds),
        wotan=expand("data/results/wotan_tls/{seed}.yaml", seed=seeds),
    output: "data/results/detections.csv"
    conda: "envs/base.yaml"
    priority: 2
    script: "scripts/aggregate_detections.py"

rule detection_method_results:
    input: 
        params=expand("data/params/{seed}.yaml", seed=seeds),
        result=expand("data/results/{method}/{seed}.yaml", seed=seeds, allow_missing=True)
    output: "data/results/{method}/detections.csv"
    conda: "envs/base.yaml"
    priority: 2
    script: "scripts/aggregate_method_detections.py"

rule plot_method_detection:
    input: "data/results/{method}/detections.csv"
    output: "figures/{method}_result.png"
    conda: "envs/base.yaml"
    priority: 3
    script: "scripts/plot_method_result.py"

rule plot_detection:
    input: "data/results/detections.csv"
    output: "figures/result.png"
    conda: "envs/base.yaml"
    priority: 3
    script: "scripts/plot_result.py"
