channels:
  - bioconda
  - conda-forge
dependencies:
  - pip
  - python=3.9
  - jax
  - numpy
  - pandas
  - astropy
  - snakemake
  - pip:
    - -e /Users/lgarcia/code/dev/nuance
    - wotan
    - lightkurve