configfile: "config.yaml"

# targets TICs
targets = [140212114, 27734884]
idxs = range(config["n"]**2)

rule all:
    input: 
        [f"data/27734884/recovered/wotan3D/results.csv" for i in idxs],
        [f"data/27734884/recovered/harmonics/results.csv" for i in idxs],
        [f"data/27734884/recovered/nuance/results.csv" for i in idxs],
        [f"data/27734884/recovered/bspline/results.csv" for i in idxs]

include: "search.smk"
include: "plots.smk"