configfile: "config.yaml"

# targets TICs
targets = [140212114, 27734884, 452793374, 29923559, 153193474, 306331621]
idxs = range(config["n"]**2)

rule all:
    input: 
        [f"test/searched/{target}.pdf" for target in targets],
        # [f"data/{target}/extra_info.yaml" for target in targets],
        # [f"test/cleaned/{target}.pdf" for target in targets]
        # [f"data/140212114/recovered/bls_bspline/{i}.params" for i in idxs]


include: "search.smk"
include: "plots.smk"