
lcs, = glob_wildcards("data/lightcurves/{lc}.csv")

rule all:
    input: [f"data/results/{lc}.yaml" for lc in lcs]

rule optimize_gp:
    input: "data/lightcurves/P10.0_R0.51_1415.9042195659338.csv"
    output: protected("data/gp.yaml")
    conda: "envs/base.yaml"
    script: "scripts/gp.py"

rule search:
    input: "data/gp.yaml", "data/lightcurves/{lc}.csv"
    output: "data/results/{lc}.yaml"
    conda: "envs/base.yaml"
    script: "scripts/search.py"

rule aggregate:
    input: ["data/result/{lc}.yaml" for lc in lcs]
    output: "data/nuance_detections.csv"
    conda: "envs/base.yaml"
    script: "scripts/aggregate.py"

