configfile: "config.yaml"


# targets TICs
idxs = range(config["n"] ** 2)

import pandas as pd

all_targets = pd.read_csv("static/tess-ultra-fast-rotators-brighter-mag14-clean.csv").Name.values
methods = {
    "bls_bspline": "bspline + BLS",
    "bls_wotan3D": "biweight + BLS",
    "bls_harmonics": "harmonics + BLS",
    "bens": "sinusoids + BLS",
    "nuance": "nuance",
}

rule all:
    input:
        [f"results/{method}.npy" for method in methods.keys()],
        "figures/tpfp_bars.pdf", 
        "figures/tpfp.pdf",
        # "figures/searched/1019692.pdf",
        # "figures/cleaned/1019692.pdf"

rule compute_true_false_positives:
    input: "data/{target}/info.yaml", "data/{target}/recovered/{method}/results.csv", "data/{target}/cleaned.fluxes"
    output: "data/{target}/recovered/{method}.npy",
    script: "scripts/true_false_positives.py"

rule concatenate_tf_positives:
    input: [f"data/{target}/recovered/{{method}}.npy" for target in all_targets]
    output: "results/{method}.npy"
    script: "scripts/concatenate_tf_positives.py"

rule plot_tp_fp:
    input: [f"results/{method}.npy" for method in methods.keys()]
    output: "figures/tpfp_bars.pdf", "figures/tpfp.pdf"
    params: methods=methods
    script: "scripts/plot_tpfp.py"

include: "search.smk"
include: "plots.smk"
