configfile: "config.yaml"

from scripts.make_params import make
from pathlib import Path
import yaml
import numpy as np
from os import path
from functools import partial

# DATASET CREATION
# ----------------
dataset = Path("data/params")
dataset.mkdir(exist_ok=True, parents=True)
n = 10000
np.random.seed(42)
vars = np.random.uniform(0.1, 5, size=n)
amps = np.random.uniform(0.1, 5, size=n)
for i, (var, amp) in enumerate(zip(vars, amps)):
    destination = dataset / f"{i}.yaml"
    params = make(config, delta_v=amp, tau_v=var, seed=i)
    if not path.exists(destination) or True:
        yaml.dump(params, open(destination, "w"))

# INPUT FUNCTIONS
# ---------------
def dataset_results(wildcards, which="biweight"):
    seeds, = glob_wildcards(f"data/params" + "/{seed, \d+}.yaml")
    return expand(f"data/results/{which}/{{seed}}.yaml", seed=seeds)

def dataset_params(wildcards):
    seeds, = glob_wildcards(f"data/params" + "/{seed, \d+}.yaml")
    return expand(f"data/params/{{seed}}.yaml", seed=seeds)

seeds, = glob_wildcards(f"data/params" + "/{seed, \d+}.yaml")

# DAG
# ---
wildcard_constraints:
    seed="\d+"

rule:
    input: 
        # "results/results_biweight.csv",
        # "results/results_gp.csv",
        "figures/result.pdf"

rule make_lightcurves:
    input: "data/params/{seed, \d+}.yaml"
    output: "data/lightcurves/{seed}.npy"
    priority: 0
    script: "scripts/make_lightcurve.py"

rule clean_biweight:
    input: 
        "data/params/{seed, \d+}.yaml",
        "data/lightcurves/{seed, \d+}.npy"
    output: "data/results/biweight/{seed}.yaml"
    priority: 1
    script: "scripts/clean_biweight.py"

rule clean_gp:
    input: 
        "data/params/{seed, \d+}.yaml",
        "data/lightcurves/{seed, \d+}.npy"
    output: "data/results/gp/{seed}.yaml"
    priority: 1
    script: "scripts/clean_gp.py"

rule detection_results_biweight:
    input: partial(dataset_results, which="biweight")
    output: protected("results/results_biweight.csv")
    priority: 2
    script: "scripts/aggregate_results.py"

rule detection_results_gp:
    input: partial(dataset_results, which="gp")
    output: protected("results/results_gp.csv")
    priority: 2
    script: "scripts/aggregate_results.py"

rule plot:
    input: "results/results_biweight.csv", "results/results_gp.csv"
    output: "figures/result.pdf"
    priority: 3
    script: "scripts/plot.py"
